spring:
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    # 设置页面缓存
    cache: false
    template-loader-path:
      - classpath:/templates
    mvc:
      static-path-pattern: /static/**



elasticsearch:
  cluster:
    name: myes
  ip: 192.168.139.128
  port: 9300
  pool: 5